#!/usr/bin/with-contenv bash

[[ -f /config/nzbget.conf ]] && \
  source /config/nzbget.conf &>/dev/null

[[ -z "${ScriptDir}" ]] && \
  ScriptDir=/downloads/scripts

[[ ! -e "${ScriptDir}" ]] && \
  mkdir -p "${ScriptDir}"

DIR="${ScriptDir}/mp4"
[[ ! -L "${DIR}" ]] && \
  ln -s /mp4 "${DIR}"

chown abc:abc -R "${ScriptDir}" /mp4
