#!/usr/bin/with-contenv bash

[[ -f /config/nzbget.conf ]] && \
  source /config/nzbget.conf &>/dev/null

[[ -z "${ScriptDir}" ]] && \
  ScriptDir=/downloads/scripts

[[ ! -e "${ScriptDir}" ]] && \
  mkdir -p "${ScriptDir}"

cp -R /mp4 "${ScriptDir}"
chown abc:abc -R "${ScriptDir}"
chmod +x "${SciptDir}/mp4/mp4.sh"
